In [36]:
import numpy as np
import matplotlib.pyplot as plt


In [37]:
%matplotlib inline

In [38]:
from sklearn.datasets import load_digits

digit = load_digits()

x = digit.data
y = digit.target

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size= 0.2,random_state=1)

In [41]:
# from sklearn.preprocessing import StandardScaler
# scale = StandardScaler()

In [42]:
# xtrain = scale.fit_transform(xtrain)
# xtest = scale.fit_transform(xtest)

In [43]:
from sklearn.naive_bayes import GaussianNB

In [44]:
nb = GaussianNB()

In [45]:
nb.fit(xtrain,ytrain)

GaussianNB()

In [46]:
ypred = nb.predict(xtest)

In [47]:
print(ypred)
print(ytest)

[1 5 0 7 1 0 6 1 5 4 9 8 7 8 4 6 4 3 7 4 7 8 8 6 0 7 6 1 3 7 5 5 8 3 2 8 8
 1 1 0 7 1 0 0 8 7 2 7 8 3 4 3 4 0 4 7 0 5 8 5 3 1 7 0 5 8 8 3 3 4 0 3 7 4
 7 0 2 7 7 3 1 5 3 4 1 5 5 2 5 8 2 2 2 7 0 8 1 7 4 8 3 8 1 3 2 0 8 8 8 8 3
 2 8 1 8 9 1 2 0 4 8 5 4 4 7 6 7 6 6 1 7 5 6 3 8 3 7 1 8 5 3 4 7 8 5 0 6 0
 6 3 7 6 5 6 2 2 2 3 0 7 6 5 6 4 1 0 6 0 6 4 0 9 8 8 1 2 3 1 4 0 7 6 2 9 3
 1 7 4 6 3 3 7 4 7 2 7 6 1 6 8 4 0 3 8 7 9 8 9 0 1 3 6 8 0 7 5 9 8 2 3 5 8
 0 8 7 4 0 3 3 1 6 3 3 8 9 1 6 9 0 4 2 2 7 9 1 6 7 6 5 7 1 9 3 4 0 6 4 8 5
 3 6 3 1 4 0 4 4 8 7 7 8 5 2 7 0 9 0 4 4 0 1 4 6 6 8 8 5 0 1 6 0 1 8 2 0 9
 5 6 8 0 5 0 3 1 4 7 1 7 0 6 6 8 0 8 2 6 9 9 7 7 1 7 6 4 6 1 9 4 7 1 3 7 8
 8 6 9 8 8 2 4 8 7 5 8 6 9 8 8 7 0 0 4 9 5 0 4 9 4 2 5]
[1 5 0 7 1 0 6 1 5 4 9 2 7 8 4 6 9 3 7 4 7 1 8 6 0 9 6 1 3 7 5 9 8 3 2 8 8
 1 1 0 7 9 0 0 8 7 2 7 4 3 4 3 4 0 4 7 0 5 5 5 2 1 7 0 5 1 8 3 3 4 0 3 7 4
 3 4 2 9 7 3 2 5 3 4 1 5 5 2 5 2 2 2 2 7 0 8 1 7 4 2 3 8 2 3 3 0 2 9 9 2 3
 2 8 1 1 9 1 2 0 4 8 5 4 4 7 6 7 6 6 1 7 5 6

In [48]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_recall_fscore_support

In [49]:
acc = accuracy_score(ypred,ytest)
print(acc)

0.8527777777777777


In [50]:
classir = classification_report(ypred,ytest)

In [51]:
print(classir)

              precision    recall  f1-score   support

           0       0.95      0.98      0.96        42
           1       0.83      0.83      0.83        35
           2       0.64      0.96      0.77        24
           3       0.78      0.91      0.84        35
           4       0.92      0.92      0.92        38
           5       0.83      0.89      0.86        28
           6       1.00      0.97      0.99        38
           7       1.00      0.79      0.88        47
           8       0.97      0.53      0.68        53
           9       0.59      1.00      0.74        20

    accuracy                           0.85       360
   macro avg       0.85      0.88      0.85       360
weighted avg       0.88      0.85      0.85       360



In [52]:
conn = confusion_matrix(ypred,ytest)


In [53]:
print(conn)

[[41  0  0  0  1  0  0  0  0  0]
 [ 0 29  3  1  0  1  0  0  0  1]
 [ 0  0 23  1  0  0  0  0  0  0]
 [ 0  0  1 32  0  0  0  0  1  1]
 [ 1  0  0  0 35  0  0  0  0  2]
 [ 0  0  0  2  0 25  0  0  0  1]
 [ 0  0  0  0  1  0 37  0  0  0]
 [ 1  0  0  2  0  2  0 37  0  5]
 [ 0  6  9  3  1  2  0  0 28  4]
 [ 0  0  0  0  0  0  0  0  0 20]]


In [54]:
prfs = precision_recall_fscore_support(ypred,ytest)

In [55]:
print(prfs)

(array([0.95348837, 0.82857143, 0.63888889, 0.7804878 , 0.92105263,
       0.83333333, 1.        , 1.        , 0.96551724, 0.58823529]), array([0.97619048, 0.82857143, 0.95833333, 0.91428571, 0.92105263,
       0.89285714, 0.97368421, 0.78723404, 0.52830189, 1.        ]), array([0.96470588, 0.82857143, 0.76666667, 0.84210526, 0.92105263,
       0.86206897, 0.98666667, 0.88095238, 0.68292683, 0.74074074]), array([42, 35, 24, 35, 38, 28, 38, 47, 53, 20]))


In [56]:
from sklearn.svm import SVC

sv = SVC()

In [57]:
sv.fit(xtrain,ytrain)

SVC()

In [58]:
svpred = sv.predict(xtest)

In [59]:
accuracy = accuracy_score(svpred,ytest)

In [60]:
accuracy

0.9916666666666667

In [61]:
svcon = confusion_matrix(svpred,ytest)

In [62]:
svcon

array([[43,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 35,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 36,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 41,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 38,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 30,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 37,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 36,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 28,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  1, 33]])

In [63]:
svcla = classification_report(svpred,ytest) 

In [64]:
print(svcla)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        43
           1       1.00      1.00      1.00        35
           2       1.00      1.00      1.00        36
           3       1.00      1.00      1.00        41
           4       1.00      1.00      1.00        38
           5       1.00      0.97      0.98        31
           6       1.00      1.00      1.00        37
           7       0.97      1.00      0.99        36
           8       0.97      1.00      0.98        28
           9       0.97      0.94      0.96        35

    accuracy                           0.99       360
   macro avg       0.99      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360



In [65]:
prfs = precision_recall_fscore_support(svpred,ytest)

In [66]:
print(prfs)

(array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.97297297, 0.96551724, 0.97058824]), array([1.        , 1.        , 1.        , 1.        , 1.        ,
       0.96774194, 1.        , 1.        , 1.        , 0.94285714]), array([1.        , 1.        , 1.        , 1.        , 1.        ,
       0.98360656, 1.        , 0.98630137, 0.98245614, 0.95652174]), array([43, 35, 36, 41, 38, 31, 37, 36, 28, 35]))


In [67]:
#Step 5: Build models 
from sklearn.model_selection import KFold,cross_val_score
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn.naive_bayes import GaussianNB 
from sklearn.svm import SVC  
from sklearn.ensemble import RandomForestClassifier


In [68]:
# Spot Check Algorithms 
models = [] 
models.append(('LR', LogisticRegression())) 
models.append(('LDA', LinearDiscriminantAnalysis())) 
models.append(('KNN', KNeighborsClassifier())) 
models.append(('CART', DecisionTreeClassifier())) 
models.append(('NB', GaussianNB())) 
models.append(('SVM', SVC()))
models.append(('DecisionTree',DecisionTreeClassifier()))
models.append(('Random Forest',RandomForestClassifier()))

In [70]:
# evaluate each model in turn 
results = [] #Stores Accuracy figures
names = []  #Stores Names of Algorithms

In [74]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
for name, model in models: 
 kfold = KFold(n_splits=10, random_state=None) 
 cv_results = cross_val_score(model, xtrain, ytrain, cv=kfold, scoring='accuracy') 
 results.append(cv_results) 
 names.append(name) 
 msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std()) 
 print(msg)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


LR: 0.959620 (0.013916)
LDA: 0.952676 (0.015507)
KNN: 0.983299 (0.009933)
CART: 0.838539 (0.023601)
NB: 0.838515 (0.042972)
SVM: 0.986767 (0.007291)
DecisionTree: 0.840627 (0.021784)
Random Forest: 0.979808 (0.010097)
